version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data/
  backend:
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  postgres-db:
    driver: local
