name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-workflow-ci:
    uses: ./.github/workflows/ci.yml

  build:
    needs: call-workflow-ci
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -o main main.go

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: Add deploy step
      - name: Deploy
        run: |
          echo "Deploying..."
